### ISSUE TITLE
Why is black a dependency?

### ISSUE THREAD

**Issue by George3d6** [tryVital/vital-python#34]
`black` is present twice under both dev and normal dependencies: https://github.com/tryVital/vital-python/blob/master/pyproject.toml

It has a very restrictive version, not to mention the version between package and dev is mismatched.

This will make it a) clash with projects that actually need black as a dependency, b) makes no sense because black is likely only a dev dependency for this SDK.

Even if it weren't, why would you have two versions, one for dev and one for package?

**Comment by maitham** [comment]
Hey George! Good spot. This is a mistake, we will remove this from the pyroject.toml.

**Comment by George3d6** [comment]
to be clear, leaving it as a dev dependency should be totally fine, but in the package dependency section it will cause conflicts, as it did for me.

**Comment by maitham** [comment]
This has now been merged.
