### ISSUE TITLE
How to get a user by their client user id?

### ISSUE THREAD

**Issue by George3d6** [tryVital/vital-python#35]
At present vital users are created via a `client_user_id` -- however, it seems like the API lacks a way of identifying them by said id, `User.get` expects a (vital) `user_id`.

Is there any way to get a user by their `client_user_id` other than using `get_all` and filtering through all users?

**Comment by maitham** [comment]
You can use the `User.resolve()` endpoint 

```
def resolve(self, client_user_id: str) -> Mapping[str, str]:
        """
        Get user details from key.
        :param str client_user_id: The client user id.
        """
        return self.client.get(f"/user/key/{client_user_id}")
```
